# Generated by Django 4.0 on 2021-12-13 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0010_remove_semester_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('day', models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('saturday', 'saturday')], default='monday', max_length=50)),
                ('subject1', models.CharField(max_length=50)),
                ('subject2', models.CharField(max_length=50)),
                ('subject3', models.CharField(max_length=50)),
                ('subject4', models.CharField(max_length=50)),
                ('subject5', models.CharField(max_length=50)),
                ('subject6', models.CharField(blank=True, max_length=50, null=True)),
                ('appruve', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.course')),
                ('semster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.semester')),
            ],
        ),
        migrations.CreateModel(
            name='InternalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1_mark', models.PositiveIntegerField()),
                ('test2_mark', models.PositiveIntegerField()),
                ('seminar_mark', models.PositiveIntegerField()),
                ('attendence', models.PositiveIntegerField()),
                ('no_of_working_days', models.PositiveIntegerField()),
                ('attendence_mark', models.PositiveIntegerField()),
                ('total_seminar_mark', models.PositiveIntegerField()),
                ('total_internal_mark', models.PositiveIntegerField()),
                ('final_total_internal_mark', models.PositiveIntegerField()),
                ('semster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.semester')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Audio_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio')),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.subject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('question', models.FileField(upload_to='assignment_question')),
                ('answer', models.FileField(blank=True, null=True, upload_to='assignment_ans')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('semster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.semester')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.subject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.teacher')),
            ],
        ),
    ]
