# Generated by Django 4.0 on 2021-12-14 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_video',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
