# Generated by Django 4.0 on 2021-12-14 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_notification_approve_alter_notification_ending_date_and_more'),
        ('teacher', '0003_alter_audio_video_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalmark',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.course'),
            preserve_default=False,
        ),
    ]
