# Generated by Django 4.0 on 2021-12-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_assignment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='subject',
        ),
    ]
