# Generated by Django 4.0 on 2021-12-14 13:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_notification_approve_alter_notification_ending_date_and_more'),
        ('teacher', '0007_alter_assignment_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.course'),
            preserve_default=False,
        ),
    ]
