# Generated by Django 3.2.6 on 2022-01-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_assignment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='answer',
            field=models.FileField(blank=True, null=True, upload_to='assignment_answer'),
        ),
    ]
