# Generated by Django 4.0 on 2021-12-10 09:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20)),
                ('course_prefix', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('no_of_semsters', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('admission_fee', models.PositiveIntegerField()),
                ('tution_fee', models.PositiveIntegerField()),
                ('library_fee', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('mobile_no2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name=[('', '---------')])),
                ('house_name', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.PositiveIntegerField(blank=True, null=True)),
                ('district', models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Alappuzha', 'Alappuzha'), ('Pathanamthitta', 'Pathanamthitta'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), (' Ernakulam', ' Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), (' Kozhikode', ' Kozhikode'), ('Wayanadu', 'Wayanadu'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], default='Thrissur', max_length=40)),
                ('designation', models.CharField(max_length=60)),
                ('job_type', models.CharField(choices=[('teacher', 'teacher'), ('HOD', 'HOD')], default='teacher', max_length=50)),
                ('department_post', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=40)),
                ('other_qualifications', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_proof', models.FileField(upload_to='certificate_teacher')),
                ('mphill', models.BooleanField(default=False)),
                ('phd', models.BooleanField(default=False)),
                ('net', models.BooleanField(default=False)),
                ('year_of_experience', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='teacher_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=30)),
                ('register_no', models.CharField(max_length=30, unique=True)),
                ('application_id', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=40)),
                ('addhar_no', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12)])),
                ('dob', models.DateField()),
                ('house_name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=50)),
                ('district', models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Alappuzha', 'Alappuzha'), ('Pathanamthitta', 'Pathanamthitta'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), (' Ernakulam', ' Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), (' Kozhikode', ' Kozhikode'), ('Wayanadu', 'Wayanadu'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], default='Thrissur', max_length=40)),
                ('pincode', models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(6)])),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('mobile_no2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name=[('', '---------')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('religion', models.CharField(max_length=30)),
                ('cast', models.CharField(max_length=40)),
                ('date_of_admission', models.DateField(verbose_name=django.utils.timezone.now)),
                ('parent_name', models.CharField(max_length=50)),
                ('local_guardian', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(default='default.jpg', upload_to='register_image')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('mothers_mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('fathers_mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('admission_no', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='NonTeaching_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('mobile_no2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name=[('', '---------')])),
                ('house_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pincode', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='non_teaching_photo')),
                ('district', models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Alappuzha', 'Alappuzha'), ('Pathanamthitta', 'Pathanamthitta'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), (' Ernakulam', ' Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), (' Kozhikode', ' Kozhikode'), ('Wayanadu', 'Wayanadu'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], default='Thrissur', max_length=40)),
                ('job_type', models.CharField(choices=[('office staff', 'office staff'), ('librarian', 'librarian'), ('lab assistant', 'lab assistant'), ('other', 'other')], default='librarian', max_length=50)),
                ('post', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=40)),
                ('other_qualifications', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_proof', models.FileField(upload_to='certificate_teacher')),
                ('degree', models.BooleanField(default=False)),
                ('plus_two', models.BooleanField(default=False)),
                ('sslc', models.BooleanField(default=False)),
                ('year_of_experience', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
