# Generated by Django 4.0 on 2021-12-10 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_teacher_alter_nonteaching_staff_mobile_no2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='addhar_no',
            new_name='adhar_no',
        ),
        migrations.AddField(
            model_name='student',
            name='semster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
