# Generated by Django 4.0 on 2021-12-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_course_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
    ]
