# Generated by Django 4.0 on 2021-12-11 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.IntegerField(default=555),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nonteaching_staff',
            name='photo',
            field=models.ImageField(upload_to='staff_image'),
        ),
        migrations.AlterField(
            model_name='student',
            name='adhar_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='pincode',
            field=models.PositiveIntegerField(),
        ),
    ]
