# Generated by Django 4.0 on 2021-12-11 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_teacher_teacher_id_alter_nonteaching_staff_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonteaching_staff',
            name='staff_id',
            field=models.IntegerField(default=1111, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.IntegerField(unique=True),
        ),
    ]
