# Generated by Django 4.0 on 2021-12-12 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_nonteaching_staff_staff_id_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pincode',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
