# Generated by Django 4.0 on 2021-12-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_student_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.course'),
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
                ('syllabus', models.FileField(upload_to='syllabus')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.course')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.course')),
                ('semster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('notification', models.CharField(max_length=200)),
                ('notification_publish_date', models.DateTimeField(auto_now_add=True)),
                ('starting_date', models.DateTimeField(auto_now_add=True)),
                ('ending_date', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='notification')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.course')),
                ('semster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.semester')),
            ],
        ),
    ]
