# Generated by Django 4.0 on 2021-12-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_semester_course_syllabus_subject_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='course',
        ),
    ]
