# Generated by Django 4.0 on 2021-12-13 10:54

import account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=2021, validators=[django.core.validators.MinValueValidator(1984), account.models.max_value_current_year]),
        ),
    ]
