# Generated by Django 4.0 on 2021-12-14 03:34

import account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_student_date_of_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(default=2021, validators=[django.core.validators.MinValueValidator(1984), account.models.max_value_current_year]),
        ),
    ]
