# Generated by Django 3.2.6 on 2021-12-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_notification_approve_alter_notification_ending_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department_post',
            field=models.CharField(choices=[('teacher', 'teacher'), ('hod', 'hod')], default='teacher', max_length=100),
        ),
    ]
