# Generated by Django 3.2.6 on 2021-12-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_teacher_department_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department_post',
            field=models.CharField(max_length=100),
        ),
    ]
