# Generated by Django 3.2.6 on 2021-12-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_teacher_department_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='confirmation',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('not_confirmed', 'not_confirmed')], default='not_confirmed', max_length=20),
        ),
    ]
