# Generated by Django 4.0 on 2021-12-12 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_application_name'),
        ('account', '0008_alter_student_pincode'),
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.course'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.application'),
        ),
        migrations.DeleteModel(
            name='CourseFee',
        ),
    ]
