# Generated by Django 4.0 on 2021-12-13 22:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_student_dob'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 12, 13, 22, 4, 5, 12459, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebook',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.nonteaching_staff'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='book_file'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
