# Generated by Django 4.0 on 2021-12-13 22:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_ebook_created_date_ebook_staff_ebook_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='staff',
        ),
        migrations.AddField(
            model_name='studentbook',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 12, 13, 22, 25, 11, 83796, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
