# Generated by Django 4.0 on 2021-12-14 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_student_dob'),
        ('staff', '0003_remove_ebook_staff_studentbook_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbook',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
    ]
