# Generated by Django 4.0 on 2021-12-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_studentbook_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
