# Generated by Django 4.0 on 2021-12-12 12:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_alter_student_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('adhar_no', models.PositiveIntegerField(unique=True)),
                ('dob', models.DateField()),
                ('house_name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=50)),
                ('district', models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Alappuzha', 'Alappuzha'), ('Pathanamthitta', 'Pathanamthitta'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), (' Ernakulam', ' Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), (' Kozhikode', ' Kozhikode'), ('Wayanadu', 'Wayanadu'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], default='Thrissur', max_length=40)),
                ('pincode', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(1000000)])),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('mobile_no2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('religion', models.CharField(max_length=30)),
                ('cast', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='register_image')),
                ('course_name_previous_college', models.CharField(max_length=50)),
                ('management_or_community_status', models.CharField(choices=[('management', 'management'), ('community', 'community')], max_length=30)),
                ('appering_or_passout', models.CharField(choices=[('appering', 'appering'), ('passout', 'passout')], default='passout', max_length=20)),
                ('persentage_obtained', models.CharField(blank=True, max_length=50, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.course')),
            ],
        ),
    ]
