# Generated by Django 4.0 on 2021-12-12 13:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('adhar_no', models.PositiveIntegerField(unique=True)),
                ('dob', models.DateField()),
                ('house_name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('pincode', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(1000000)])),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='adhar_no',
        ),
        migrations.RemoveField(
            model_name='application',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='house_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='application',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='application',
            name='place',
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.basic_details'),
        ),
    ]
