# Generated by Django 4.0 on 2021-12-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_application_mobile_no_alter_application_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_details',
            name='adhar_no',
            field=models.PositiveIntegerField(),
        ),
    ]
