# Generated by Django 4.0 on 2021-12-12 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_basic_details_adhar_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basic_details',
            name='application_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.basic_details'),
        ),
    ]
