# Generated by Django 4.0 on 2021-12-12 15:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_application_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_details',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
