# Generated by Django 4.0 on 2021-12-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_basic_details_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.basic_details'),
        ),
    ]
