# Generated by Django 4.0 on 2021-12-13 06:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_semester_course'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('student', '0007_alter_application_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChalanGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_of_this_chalan', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=100)),
                ('register_no', models.IntegerField()),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.PositiveIntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreacdemicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sslc_school_name', models.CharField(max_length=100)),
                ('sslc_Persentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(101)])),
                ('sslc_passout_year', models.DateField()),
                ('higher_secondary_school_name', models.CharField(max_length=100)),
                ('hss_persentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(101)])),
                ('hss_passout_year', models.DateField(default=2021, validators=[django.core.validators.MinValueValidator(1984), student.models.max_value_current_year])),
                ('college_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('college_passout_year', models.DateField(blank=True, null=True)),
                ('year_gap', models.PositiveIntegerField(blank=True, null=True)),
                ('institution_last_studied', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('replay', models.TextField(blank=True, default='not replayed', null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('replay_date', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
    ]
