# Generated by Django 4.0 on 2021-12-14 04:15

import django.core.validators
from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_chalangeneration_preacdemicdetails_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preacdemicdetails',
            name='college_passout_year',
            field=models.IntegerField(blank=True, default=2021, null=True, validators=[django.core.validators.MinValueValidator(1984), student.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='preacdemicdetails',
            name='hss_passout_year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), student.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='preacdemicdetails',
            name='hss_persentage',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='preacdemicdetails',
            name='sslc_Persentage',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='preacdemicdetails',
            name='sslc_passout_year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), student.models.max_value_current_year]),
        ),
    ]
