# Generated by Django 4.0 on 2021-12-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_preacdemicdetails_college_passout_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preacdemicdetails',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
