# Generated by Django 4.0 on 2021-12-14 07:48

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('student', '0010_preacdemicdetails_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalangeneration',
            name='chalan_no',
            field=models.IntegerField(default=10001),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chalangeneration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='preacdemicdetails',
            name='hss_persentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(101)]),
        ),
    ]
