# Generated by Django 4.0 on 2021-12-14 07:51

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_chalangeneration_chalan_no_chalangeneration_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preacdemicdetails',
            name='college_passout_year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preacdemicdetails',
            name='hss_passout_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='preacdemicdetails',
            name='sslc_Persentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(101)]),
        ),
    ]
