# Generated by Django 4.0 on 2021-12-14 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_student_date_of_admission_alter_student_dob'),
        ('student', '0012_alter_preacdemicdetails_college_passout_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preacdemicdetails',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
    ]
