# Generated by Django 4.0 on 2021-12-14 08:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_preacdemicdetails_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='preacdemicdetails',
            name='sslc_register_no',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
