# Generated by Django 4.0 on 2021-12-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_preacdemicdetails_sslc_register_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preacdemicdetails',
            name='sslc_register_no',
        ),
    ]
