# Generated by Django 4.0 on 2021-12-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_remove_preacdemicdetails_sslc_register_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chalangeneration',
            name='chalan_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
