# Generated by Django 3.2.6 on 2022-01-03 04:18

import django.core.validators
from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_chalangeneration_chalan_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preacdemicdetails',
            name='sslc_passout_year',
            field=models.IntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), student.models.max_value_current_year]),
        ),
    ]
